/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 rocket_3d.glb 
*/

import React, { useRef } from "react";
import { MeshReflectorMaterial, useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Rocket3d(props: any) {
   // @ts-ignore
   const { nodes, materials } = useGLTF("/rocket_3d.glb");

   return (
      <group {...props} dispose={null} castShadow receiveShadow>
         <group
            position={[0, 1.831, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            castShadow
            receiveShadow
         >
            <mesh
               geometry={nodes.Plane.geometry}
               material={materials.metalic_white}
               material-color="white"
               castShadow
            />
            <mesh
               geometry={nodes.Plane_1.geometry}
               material={materials.metalic_orange}
               material-color="#cb6815"
               castShadow
            />
            <mesh
               geometry={nodes.Plane_2.geometry}
               material={materials.metalic_orange}
               material-color="#cb6815"
               castShadow
            />
            <mesh
               geometry={nodes.Plane_3.geometry}
               material={materials.metalic_grey}
               material-color="#eeeeee"
               castShadow
            />
         </group>
         <mesh
            geometry={nodes.wing_2.geometry}
            material={materials.metalic_orange}
            position={[0.662, 1.796, 0]}
            rotation={[0, 0, -0.515]}
            scale={[1, 1, 0.509]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.wing_1.geometry}
            material={materials.metalic_orange}
            position={[0.167, 0.857, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 1.117, 1]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.wing_2.geometry}
            material={materials.metalic_orange}
            position={[-0.662, 1.796, 0]}
            rotation={[0, 3, -0.515]}
            scale={[1, 1, 0.509]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.wing_1.geometry}
            material={materials.metalic_orange}
            position={[-0.167, 0.857, 0]}
            rotation={[Math.PI / 2, 0, 3.142]}
            scale={[1, 1.117, 1]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.wing_3.geometry}
            material={materials.metalic_orange}
            position={[0, 1.019, 0.293]}
            rotation={[0, 0, -Math.PI / 2]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.wing_3.geometry}
            material={materials.metalic_orange}
            position={[0, 1.019, -0.293]}
            rotation={[0, 3.142, -Math.PI / 2]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.glass.geometry}
            material={materials.glass}
            position={[0, 2.212, 0.477]}
            rotation={[-0.181, 0, 0]}
            scale={[0.765, 0.765, 0.754]}
            material-color="#061640"
            castShadow
            receiveShadow
         />
         {/* <mesh
            geometry={nodes.line.geometry}
            material={materials.metalic_grey}
            position={[0.167, 0.857, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 1.117, 1]}
            castShadow
            receiveShadow
         /> */}
         <mesh
            geometry={nodes.wing_down.geometry}
            material={materials.metalic_grey}
            position={[0.167, 0.857, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 1.117, 1]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.wing_down.geometry}
            material={materials.metalic_grey}
            position={[-0.167, 0.857, 0]}
            rotation={[Math.PI / 2, 0, 3.142]}
            scale={[1, 1.117, 1]}
            castShadow
            receiveShadow
         />
         <mesh
            geometry={nodes.vida.geometry}
            material={materials.metalic_grey}
            position={[0, 2.297, 0.654]}
            castShadow
            receiveShadow
         />
      </group>
   );
}

useGLTF.preload("/rocket_3d.glb");
